package softwareinclude.ro.securitylockandroid.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ACCOUNT_DATA_MODEL.
 */
public class AccountDataModel {

    private Long id;
    /** Not-null value. */
    private String accountName;
    /** Not-null value. */
    private String accountPassword;
    /** Not-null value. */
    private String accountDetails;

    public AccountDataModel() {
    }

    public AccountDataModel(Long id) {
        this.id = id;
    }

    public AccountDataModel(Long id, String accountName, String accountPassword, String accountDetails) {
        this.id = id;
        this.accountName = accountName;
        this.accountPassword = accountPassword;
        this.accountDetails = accountDetails;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getAccountName() {
        return accountName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setAccountName(String accountName) {
        this.accountName = accountName;
    }

    /** Not-null value. */
    public String getAccountPassword() {
        return accountPassword;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setAccountPassword(String accountPassword) {
        this.accountPassword = accountPassword;
    }

    /** Not-null value. */
    public String getAccountDetails() {
        return accountDetails;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setAccountDetails(String accountDetails) {
        this.accountDetails = accountDetails;
    }

}
